/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import com.lowagie.text.html.HtmlTags;
import dao.Dao;
import java.awt.Color;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import vo.Usuario;

/**
 *
 * @author jonas
 */
public class Cadastro extends javax.swing.JFrame {

    public Cadastro() {
        initComponents();
        tf_codigo.disable();
    }
    SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss dd/MM/yyyy");
    Usuario usuario = null;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lb_aviso_codigo = new javax.swing.JLabel();
        tf_codigo = new javax.swing.JTextField();
        tf_nome = new javax.swing.JTextField();
        tf_apelido = new javax.swing.JTextField();
        tf_email = new javax.swing.JTextField();
        tf_endereco = new javax.swing.JTextField();
        tf_bairro = new javax.swing.JTextField();
        tf_cpf_cnpj = new javax.swing.JFormattedTextField();
        tf_celular = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        pf_senha2 = new javax.swing.JPasswordField();
        bt_limpar = new javax.swing.JButton();
        bt_buscar = new javax.swing.JButton();
        bt_sair = new javax.swing.JButton();
        bt_deletar = new javax.swing.JButton();
        bt_salvar = new javax.swing.JButton();
        tf_nm_cidade = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tf_complemento = new javax.swing.JTextArea();
        lb_senha1 = new javax.swing.JLabel();
        pf_senha1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(100, 100));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel1.setText("Código.:");
        jLabel1.setAlignmentX(0.5F);
        jLabel1.setMaximumSize(null);
        jLabel1.setPreferredSize(null);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 32, 77, -1));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel2.setText("Nome.:");
        jLabel2.setAlignmentX(0.5F);
        jLabel2.setMaximumSize(null);
        jLabel2.setPreferredSize(null);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 82, 56, -1));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel4.setText("Apelido.:");
        jLabel4.setAlignmentX(0.5F);
        jLabel4.setMaximumSize(null);
        jLabel4.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 79, -1));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel5.setText("CPF .:");
        jLabel5.setAlignmentX(0.5F);
        jLabel5.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, -1, -1));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel6.setText("Celular.:");
        jLabel6.setAlignmentX(0.5F);
        jLabel6.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 80, -1));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel7.setText("Email .:");
        jLabel7.setAlignmentX(0.5F);
        jLabel7.setMaximumSize(null);
        jLabel7.setPreferredSize(null);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 80, -1));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel8.setText("Endereço.:");
        jLabel8.setAlignmentX(0.5F);
        jLabel8.setMaximumSize(null);
        jLabel8.setPreferredSize(null);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 110, -1));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel9.setText("Complemento.:");
        jLabel9.setAlignmentX(0.5F);
        jLabel9.setMaximumSize(null);
        jLabel9.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 130, -1));

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel10.setText("Bairro.:");
        jLabel10.setAlignmentX(0.5F);
        jLabel10.setMaximumSize(null);
        jLabel10.setPreferredSize(new java.awt.Dimension(150, 30));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 80, -1));

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel12.setText("Cidade.:");
        jLabel12.setAlignmentX(0.5F);
        jLabel12.setMaximumSize(null);
        jLabel12.setPreferredSize(null);
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 110, -1));

        lb_aviso_codigo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_aviso_codigo.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(lb_aviso_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 570, 20));

        tf_codigo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tf_codigo.setForeground(new java.awt.Color(255, 0, 51));
        tf_codigo.setMaximumSize(new java.awt.Dimension(100, 100));
        tf_codigo.setPreferredSize(new java.awt.Dimension(120, 30));
        tf_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_codigoActionPerformed(evt);
            }
        });
        getContentPane().add(tf_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 34, 70, -1));

        tf_nome.setMaximumSize(new java.awt.Dimension(100, 100));
        tf_nome.setMinimumSize(null);
        tf_nome.setPreferredSize(new java.awt.Dimension(120, 30));
        tf_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nomeActionPerformed(evt);
            }
        });
        getContentPane().add(tf_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 85, 240, -1));

        tf_apelido.setMaximumSize(new java.awt.Dimension(100, 100));
        tf_apelido.setMinimumSize(null);
        tf_apelido.setPreferredSize(new java.awt.Dimension(121, 30));
        getContentPane().add(tf_apelido, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 240, -1));

        tf_email.setMaximumSize(new java.awt.Dimension(100, 100));
        tf_email.setMinimumSize(null);
        tf_email.setPreferredSize(new java.awt.Dimension(120, 30));
        getContentPane().add(tf_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 240, -1));

        tf_endereco.setMaximumSize(new java.awt.Dimension(100, 100));
        tf_endereco.setMinimumSize(null);
        tf_endereco.setPreferredSize(new java.awt.Dimension(120, 30));
        tf_endereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_enderecoActionPerformed(evt);
            }
        });
        getContentPane().add(tf_endereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 240, -1));

        tf_bairro.setMaximumSize(new java.awt.Dimension(100, 100));
        tf_bairro.setMinimumSize(null);
        tf_bairro.setPreferredSize(new java.awt.Dimension(121, 30));
        getContentPane().add(tf_bairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 290, -1));

        try {
            tf_cpf_cnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(tf_cpf_cnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 290, 30));

        try {
            tf_celular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(tf_celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 290, 30));

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel13.setText("R Senha.:");
        jLabel13.setAlignmentX(0.5F);
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 80, -1));

        pf_senha2.setMaximumSize(new java.awt.Dimension(100, 100));
        pf_senha2.setMinimumSize(null);
        pf_senha2.setPreferredSize(new java.awt.Dimension(120, 30));
        getContentPane().add(pf_senha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 240, -1));

        bt_limpar.setText("Limpar");
        bt_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_limparActionPerformed(evt);
            }
        });
        getContentPane().add(bt_limpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, -1, -1));

        bt_buscar.setText("Buscar");
        bt_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_buscarActionPerformed(evt);
            }
        });
        getContentPane().add(bt_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 500, -1, -1));

        bt_sair.setText("Sair");
        bt_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_sairActionPerformed(evt);
            }
        });
        getContentPane().add(bt_sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, -1, -1));

        bt_deletar.setText("Deletar");
        bt_deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deletarActionPerformed(evt);
            }
        });
        getContentPane().add(bt_deletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 500, -1, -1));

        bt_salvar.setText("Salvar");
        bt_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salvarActionPerformed(evt);
            }
        });
        getContentPane().add(bt_salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, -1, -1));
        getContentPane().add(tf_nm_cidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 240, 30));

        tf_complemento.setColumns(20);
        tf_complemento.setRows(5);
        jScrollPane1.setViewportView(tf_complemento);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 290, 140));

        lb_senha1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lb_senha1.setText("Senha.:");
        lb_senha1.setAlignmentX(0.5F);
        lb_senha1.setMaximumSize(null);
        lb_senha1.setPreferredSize(null);
        getContentPane().add(lb_senha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 80, -1));

        pf_senha1.setMaximumSize(new java.awt.Dimension(100, 100));
        pf_senha1.setMinimumSize(null);
        pf_senha1.setPreferredSize(new java.awt.Dimension(120, 30));
        getContentPane().add(pf_senha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 240, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Dados de Acesso:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, -1));

        jLabel11.setBackground(new java.awt.Color(233, 198, 130));
        jLabel11.setForeground(new java.awt.Color(158, 214, 245));
        jLabel11.setBorder(javax.swing.BorderFactory.createMatteBorder(100, 100, 100, 100, new java.awt.Color(167, 183, 193)));
        jLabel11.setOpaque(true);
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 370, 190));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/39cb08d519356d0eee057dd67ef1f610.jpg"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 820, 540));

        setSize(new java.awt.Dimension(838, 573));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tf_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_codigoActionPerformed

    private void tf_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nomeActionPerformed

    private void tf_enderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_enderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_enderecoActionPerformed

    private void bt_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_sairActionPerformed
        dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_bt_sairActionPerformed

    private void bt_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_buscarActionPerformed
        buscarUsuario();
    }//GEN-LAST:event_bt_buscarActionPerformed

    private void bt_deletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deletarActionPerformed
        deletaUsuario(usuario);
    }//GEN-LAST:event_bt_deletarActionPerformed

    private void bt_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salvarActionPerformed
        salvarUsuario();
    }//GEN-LAST:event_bt_salvarActionPerformed

    private void bt_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_limparActionPerformed
        System.out.println(tf_cpf_cnpj.getText());
        limpaFields(Color.WHITE);

        tf_codigo.disable();

    }//GEN-LAST:event_bt_limparActionPerformed

    private void deletaUsuario(Usuario us) {
        if (tf_codigo.isEnabled() && pf_senha1.getText().length()>3) {
            try {
            us.setId(Integer.parseInt(tf_codigo.getText()));
            if (new Dao().removeUsuario(us)) {
                limpaFields(Color.WHITE);
                tf_codigo.disable();
                JOptionPane.showMessageDialog(null, "Usuario Removido com Sucesso");
                return;
            }
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Código nao está preenchido");
                return;
            }
            JOptionPane.showMessageDialog(null, "FALHA AO REMOVER USUARIO");
        }

    }

    private void salvarUsuario() {

        Usuario us = new Usuario();

        if (tf_nome.getText().length() < 5) {
            JOptionPane.showMessageDialog(null, "Nome tem que pelo menos 5 Caracters !");
            tf_nome.requestFocus();
            return;
        }
        if (tf_endereco.getText().length() < 3) {
            JOptionPane.showMessageDialog(null, "Endereço Invalido !");
            tf_endereco.requestFocus();
            return;
        }
        if (tf_cpf_cnpj.getText().equals("   .   .   -")) {
            JOptionPane.showMessageDialog(null, "CPF / CNPJ Invalido !");
            tf_cpf_cnpj.requestFocus();
            return;
        }
        if (tf_nm_cidade.getText().length() < 3) {
            JOptionPane.showMessageDialog(null, "Informe uma Cidade !");
            tf_nm_cidade.requestFocus();
            return;
        }
        if (tf_email.getText().indexOf("@") < 2 | tf_email.getText().indexOf(".") < 3) {                   // teste endereço email
            JOptionPane.showMessageDialog(null, "Informe um endereço de email válido!");
            tf_email.requestFocus();
            return;
        }
        if (!pf_senha1.getText().equals(pf_senha2.getText()) || pf_senha1.getText().length() < 3) {                                       // teste senhas
            JOptionPane.showMessageDialog(null, "As Senhas Precisam ser Iguais! ");
            pf_senha2.requestFocus();
            return;
        }

        us.setApelido(tf_apelido.getText());
        us.setBairro(tf_bairro.getText());
        us.setCidade(tf_nm_cidade.getText()); // verificar
        us.setComplemento(tf_complemento.getText());
        us.setCpf_cnpj(tf_cpf_cnpj.getText());
        us.setData_cadastro(sdf.format(new Date()));
        us.setEmail(tf_email.getText());
        us.setEndereco(tf_endereco.getText());
        us.setTelefone(tf_celular.getText());
        us.setNome(tf_nome.getText());
        us.setSenha(pf_senha2.getText());

        if (tf_codigo.isEnabled()) {
            us.setId(Integer.parseInt(tf_codigo.getText()));
            if (new Dao().atualisaUsuario(us)) {
                limpaFields(Color.WHITE);
                tf_codigo.disable();
                JOptionPane.showMessageDialog(null, "Usuario Atualizado !\nDados de Login: \n\nEmail:   " + us.getEmail() + "\nSenha:   " + us.getSenha());
                return;
            }
        } else if (new Dao().salvaUsuario(us)) {
            limpaFields(Color.WHITE);
            JOptionPane.showMessageDialog(null, "Usuario Salvo !\nDados de Login: \n\nEmail:   " + us.getEmail() + "\nSenha:   " + us.getSenha());
            return;
        }
        JOptionPane.showMessageDialog(null, "ERRO AO SALVAR / ATUALIZAR USUARIO");
    }

    private void buscarUsuario() {

        Integer codigo = null;
        Usuario user = new Usuario();

        if (tf_codigo.isEnabled()) {
            if (tf_codigo.getText().length() > 0) {
                try {
                    codigo = Integer.parseInt(tf_codigo.getText().trim());
                    user = new Dao().buscaUsuario(codigo);
                } catch (Exception e) {
                    limpaFields(Color.WHITE);
                    lb_aviso_codigo.setText("Somente Numeros no Campo Código !!");
                    tf_codigo.disable();

                    return;
                }
            } else if (tf_email.getText().length() > 0) {
                user = new Dao().buscaUsuario(tf_email.getText().trim());
            } else if (!tf_cpf_cnpj.getText().equals("   .   .   -  ")) {
                user = new Dao().buscaUsuario(tf_cpf_cnpj.getText().trim());
            }

        } else {
            limpaFields(Color.WHITE);                                                              // LImpar oque tiver setado
            
            tf_codigo.enable();
            tf_codigo.requestFocus();
            tf_codigo.setBackground(Color.LIGHT_GRAY);
            tf_email.setBackground(Color.LIGHT_GRAY);
            tf_cpf_cnpj.setBackground(Color.LIGHT_GRAY);
            lb_aviso_codigo.setText("Informe o algum dado nos Campos Marcados");
            return;
        }

        lb_aviso_codigo.setText("");

        if (user.getId() != null) {                                                 // VERIFICA SE EXISTE NO BANCO
            tf_codigo.setForeground(Color.red);
            tf_codigo.setText(user.getId().toString());
            tf_apelido.setText(user.getApelido());
            tf_bairro.setText(user.getBairro());
            tf_complemento.setText(user.getComplemento());
            tf_cpf_cnpj.setText(user.getCpf_cnpj());
            tf_email.setText(user.getEmail());
            tf_endereco.setText(user.getEndereco());
            tf_nm_cidade.setText(user.getCidade());
            tf_nome.setText(user.getNome());
            tf_celular.setText(user.getTelefone());
            pf_senha1.setText(user.getSenha());
            pf_senha2.setText(user.getSenha());
            bt_deletar.enable();
            usuario = user;
            bt_salvar.setText("Atualizar");
            //tf_codigo.disable();

        } else {
            JOptionPane.showMessageDialog(null, "Usuario nao encontrado");
        }
    }

    private void limpaFields(Color cor) {
        for (int i = 0; i < getContentPane().getComponentCount(); i++) {
            //varre todos os componentes
            Component c = getContentPane().getComponent(i);
            if (c instanceof JTextField) {
                //apaga os valores
                JTextField field = (JTextField) c;
                field.setBackground(cor);
                field.setText("");
            }
        }
        tf_complemento.setText("");
        lb_aviso_codigo.setText("");
        tf_celular.setText("");
        bt_salvar.setText("Salvar");
        bt_deletar.disable();
        tf_codigo.setText("");
        tf_email.setText("");
        tf_cpf_cnpj.setText("");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_buscar;
    private javax.swing.JButton bt_deletar;
    private javax.swing.JButton bt_limpar;
    private javax.swing.JButton bt_sair;
    private javax.swing.JButton bt_salvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_aviso_codigo;
    private javax.swing.JLabel lb_senha1;
    private javax.swing.JPasswordField pf_senha1;
    private javax.swing.JPasswordField pf_senha2;
    private javax.swing.JTextField tf_apelido;
    private javax.swing.JTextField tf_bairro;
    private javax.swing.JFormattedTextField tf_celular;
    private javax.swing.JTextField tf_codigo;
    private javax.swing.JTextArea tf_complemento;
    private javax.swing.JFormattedTextField tf_cpf_cnpj;
    private javax.swing.JTextField tf_email;
    private javax.swing.JTextField tf_endereco;
    private javax.swing.JTextField tf_nm_cidade;
    private javax.swing.JTextField tf_nome;
    // End of variables declaration//GEN-END:variables
}
