/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import dao.Dao;
import javax.swing.JOptionPane;
import vo.Controlador;
import vo.Usuario;

/**
 *
 * @author jonas
 */
public class CadastroControlador extends javax.swing.JFrame {

    Usuario user = null;
    Dao dao = new Dao();
    public CadastroControlador(Usuario user) {
        this.user = user;
        initComponents();
        this.setTitle("Gerenciar @> "+user.getNome().toUpperCase());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_senha = new javax.swing.JTextField();
        tf_ns = new javax.swing.JTextField();
        bt_remover = new javax.swing.JButton();
        bt_sair = new javax.swing.JButton();
        lb_informacao = new javax.swing.JLabel();
        lb_img_fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Adicionar");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel2.setText("Numero de Série");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 8, -1, -1));

        jLabel3.setText("Senha");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 8, -1, -1));

        tf_senha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tf_senha.setMargin(new java.awt.Insets(0, 0, 0, 0));
        tf_senha.setPreferredSize(new java.awt.Dimension(8, 25));
        getContentPane().add(tf_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 28, 100, 30));

        tf_ns.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tf_ns.setMargin(new java.awt.Insets(0, 0, 0, 0));
        tf_ns.setPreferredSize(new java.awt.Dimension(8, 25));
        getContentPane().add(tf_ns, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 28, 100, 30));

        bt_remover.setText("Remover");
        bt_remover.setOpaque(false);
        bt_remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_removerActionPerformed(evt);
            }
        });
        getContentPane().add(bt_remover, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        bt_sair.setText("Sair");
        bt_sair.setOpaque(false);
        bt_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_sairActionPerformed(evt);
            }
        });
        getContentPane().add(bt_sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        lb_informacao.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        lb_informacao.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(lb_informacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 65, 310, 20));

        lb_img_fundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_img_fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/39cb08d519356d0eee057dd67ef1f610.jpg"))); // NOI18N
        lb_img_fundo.setPreferredSize(new java.awt.Dimension(344, 120));
        getContentPane().add(lb_img_fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 150));

        setSize(new java.awt.Dimension(359, 189));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      adicionarControlador();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bt_removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_removerActionPerformed
        removeControlador();
    }//GEN-LAST:event_bt_removerActionPerformed

    private void bt_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_sairActionPerformed
        dispose();
        new Principal(user).setVisible(true);
    }//GEN-LAST:event_bt_sairActionPerformed
public void adicionarControlador(){
    Controlador controlador = new Controlador();
    if(tf_ns.getText().length() < 4 | tf_senha.getText().length()<4){
        //JOptionPane.showMessageDialog(null, "Parametros invalidos, Obrigatório 4 digitos em cada Campo!");
        lb_informacao.setText(" Obrigatório Minino 4 digitos em cada Campo !");
        return;
    }
    try{
    controlador.setNumero_serie(Integer.parseInt(tf_ns.getText().trim()));
    controlador.setSenha_serie(Integer.parseInt(tf_senha.getText().trim()));
    if(dao.validaConstrolador(controlador)){
         if(dao.relacionaConstrolador(controlador, user)){
             //JOptionPane.showMessageDialog(null, "Controlador Adicionado com Sucesso!!!");
             lb_informacao.setText("Controlador Adicionado com Sucesso !!!");
         }
    }else {
        //JOptionPane.showMessageDialog(null,"Numero de Série ou Senha incorretos.");
         lb_informacao.setText("Numero de Série ou Senha incorretos...");
    }
    }catch(Exception e){
       //JOptionPane.showMessageDialog(null, "Informe Somente Numeros!!");
        lb_informacao.setText("Informe Somente Numeros em ambos os Campos !!!");
    }
}
public void removeControlador(){
    Controlador controlador = new Controlador();
    if(tf_ns.getText().length() < 4 ){
        //JOptionPane.showMessageDialog(null, "Parametros invalidos, Obrigatório 4 digitos em cada Campo!");
        lb_informacao.setText(" Obrigatório Minino 4 digitos em cada Campo !");
        
        return;
    }
    try{
    controlador.setNumero_serie(Integer.parseInt(tf_ns.getText().trim()));
    controlador.setSenha_serie(Integer.parseInt(tf_senha.getText().trim()));
    if(dao.validaConstrolador(controlador)){
         if(dao.removeConstrolador(controlador, user)){
             //JOptionPane.showMessageDialog(null, "Controlador Removido com Sucesso!!!");
             lb_informacao.setText("Controlador Removido com Sucesso!!!");
         }
    }else {
        //JOptionPane.showMessageDialog(null,"Numero de Série ou Senha incorretos.");
        lb_informacao.setText("Numero de Série ou Senha incorretos...");
    }
    }catch(Exception e){
      // JOptionPane.showMessageDialog(null, "Informe Somente Numeros!!");
      lb_informacao.setText("Informe Somente Numeros em ambos os Campos !!!");
    }
}
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_remover;
    private javax.swing.JButton bt_sair;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lb_img_fundo;
    private javax.swing.JLabel lb_informacao;
    private javax.swing.JTextField tf_ns;
    private javax.swing.JTextField tf_senha;
    // End of variables declaration//GEN-END:variables
}
